version: '3.7'
services:
  mongodb:
    image: mongo:4.2.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: etutor
      MONGO_INITDB_ROOT_PASSWORD: rotute
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  mongodb_data_container: