version: '3.7'
services:
  mongodb:
    image: mongo:4.2.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: etutor
      MONGO_INITDB_ROOT_PASSWORD: rotute
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: