server:
  port: 8080
security:
  jwt:
    #    100 days
    expirationTime: 8640000000
    secretKey: sflkj12p4asdifasdfsdfsadfsadfsadfqwer123412

zuul:
  prefix: /api
  routes:
    user_app:
      path: /user/**
      serviceId: user_app
      strip-prefix: false
microservices:
  user:
    url: http://localhost:8090

user_app:
  ribbon:
    listOfServers: http://localhost:8090
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG